name: 01 - Building Blocks
on: push, workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello,World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: "I will fail"
      - name: Say goodbye
        run: "Goodbye" 
